### ISSUE TITLE
Strange behaviour without IPFS Companion

### ISSUE THREAD

**Issue by fsdiogo** [ipfs-shipyard/ipfs-share-files#22] opened 2018-08-31 17:07 UTC
When using the app with IPFS Companion everything works great 🌟

But a simple app like this should require the minimum amount of _setup_, that being said it should work out-of-the-box with just an IPFS daemon running.

Something strange is happening. Steps to reproduce:

1. Disable the IPFS Companion if it's active
2. Fire up an IPFS daemon in the terminal
3. Start the app and upload a single file -- it should upload successfully and generate a share link
4. Try to upload another file -- it uploads but it doesn't generate another share link as it should (and does with Companion) because the request hangs forever:
```
http://127.0.0.1:5001/api/v0/object/patch/add-link?arg=QmPvs3XyQqFY8sprbS6A18EqCS1b6A2FwKL8tx4DEjVRUD&arg=package.json&arg=QmdXb9kCfLv4bGHRiiFStC66JSH36Gr2y7j7hW9cnrZqUm&stream-channels=true
```

The problem should come from this func:
https://github.com/ipfs-shipyard/ipfs-share-files/blob/3d8c417ffc0c2ababd771e1277afbecd851e1a55/src/lib/files.js#L47-L56

I can't understand why it works with Companion & it works the first time the func is called, it generates the share link. But when calling again it hangs. It also happens if you try to upload multiple files the first time, I think there is something wrong when creating the new `unixfs-dir` and/or adding links to it.

Ideas? @ipfs-shipyard/gui

**Comment by lidel** [comment] 2018-08-31 20:15
@fsdiogo I am not sure if I reproduced the same error :upside_down_face: , but adding multiple files worked for me until I hit [this known problem with go-ipfs+js-ipfs-api](https://github.com/ipfs/js-ipfs-api/issues/797). 

UI froze at this state (I can't remove greyed one):

> ![screenshot_29](https://user-images.githubusercontent.com/157609/44933176-7a9b4400-ad68-11e8-8dde-8fd78e859d77.png)
 
You can try reproducing it by adding multiple files and then  [upload-multiple-files-via-browser-ipfs-api-bug-demo.zip](https://github.com/ipfs-shipyard/ipfs-share-files/files/2341400/upload-multiple-files-via-browser-ipfs-api-bug-demo.zip) (this .zip triggered the go-ipfs big for me, but due to the nature of the bug it may not work the same on every machine).

As you can read in https://github.com/ipfs/js-ipfs-api/issues/797#issuecomment-401469158 there is no known workaround for HTML context. The only thing we can do is to count input arguments and detect if `files.add` result list is too short and display error to the user. I described all the steps in https://github.com/ipfs-shipyard/ipfs-webui/pull/769#issuecomment-416900828.

You can add error handling in the app, but in the long run we probably should fix this upstream in js-ipfs-api ((https://github.com/ipfs/js-ipfs-api/issues/797) 

PS. It probably worked with Companion because WebExtension has more powerful APIs than HTML JS and  [applies a fix for `/api/v0/add`](https://github.com/ipfs-shipyard/ipfs-companion/blob/37ac47ddb62e992d4300a6991eb7ab29494e5f5e/add-on/src/lib/ipfs-request.js#L81-L91).

**Comment by lidel** [comment] 2018-09-03 13:17
AFAIK we can't fix it from the app itself: website's  JS can't set `Connection` nor `Expect` headers :(
However, I've added a new workaround for go-ipfs issue (https://github.com/ipfs-shipyard/ipfs-companion/pull/562) to IPFS Companion.  When merged, it will finally fix issue under Chrome if user has our extension enabled. 

See [the PR](https://github.com/ipfs-shipyard/ipfs-companion/pull/562) for more details.

**Comment by jessicaschilling** [comment] 2021-02-01 21:48
@lidel can we close this?

**Comment by lidel** [comment] 2021-02-02 00:28
Yup, this is no longer relevant as we deprecated `window.ipfs`

**Closed by lidel** 2021-02-02 00:28 UTC
Labels: need/triage
